name: PhyloTracer
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.13
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - biopython
  - ete3
  - pillow
  - pyqt=5
  - pypdf>=3.0.0
  - pip:
      - phyde>=1.0.2
